window.FR13_TEMPLATE = {
  "templateId": "FR13",
  "templateName": "Emniyet Olayları Denetimi Kontrol Formu",
  "formatVersion": "1.1",
  "totalAAD": 58,
  "data": [
    {
      "id": 1,
      "htmlKey": "fr13-zrs-1-aad01",
      "questionNo": 1,
      "questionCode": "SHGM.EYU.ZRS.1",
      "shortCode": "ZRS.1",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 5; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 4(2)",
      "question": "Kuruluş, zorunlu raporlama sistemi kurmuş mu?",
      "atomicCriterion": "Olay raporlama sistemi, işletme el kitaplarında (OM-A, MSM vb.) Emniyet Yönetim Sisteminin (SMS) entegre bir parçası olarak tanımlanmıştır",
      "auditorGuidance": "İncelenecek Husus: Olay raporlama sisteminin, işletmenin Emniyet Yönetim Sisteminin (SMS) entegre bir parçası olarak resmiyet kazandığının teyidi.\n\nKabul Edilebilir Kanıtlar: İşletme El Kitabı (OM-A Bölüm 11 vb.) veya SMS El Kitabı ilgili bölüm referansları.",
      "sourcePage": 3
    },
    {
      "id": 2,
      "htmlKey": "fr13-zrs-1-aad02",
      "questionNo": 1,
      "questionCode": "SHGM.EYU.ZRS.1",
      "shortCode": "ZRS.1",
      "aadCode": "AAD02",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 5; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 4(2)",
      "question": "Kuruluş, zorunlu raporlama sistemi kurmuş mu?",
      "atomicCriterion": "Sistemin yasal dayanağı olarak güncel SHT-OLAY, SDED-2022/1 ve Reg. (EU) No. 376/2014 mevzuatlarına açık atıf yapılmıştır",
      "auditorGuidance": "İncelenecek Husus: Kurulan sistemin yasal dayanağının ulusal ve uluslararası güncel mevzuata dayandırıldığının dökümantasyon üzerinden teyidi.\n\nKabul Edilebilir Kanıtlar: İlgili el kitabının \"Referanslar\" veya \"Yasal Dayanak\" bölümünde SHT-OLAY, SDED-2022/1 ve Reg. (EU) No. 376/2014 atıflarının varlığı.",
      "sourcePage": 4
    },
    {
      "id": 3,
      "htmlKey": "fr13-zrs-1-aad03",
      "questionNo": 1,
      "questionCode": "SHGM.EYU.ZRS.1",
      "shortCode": "ZRS.1",
      "aadCode": "AAD03",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 5; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 4(2)",
      "question": "Kuruluş, zorunlu raporlama sistemi kurmuş mu?",
      "atomicCriterion": "Emniyet hedefleriyle uyumlu olacak şekilde, raporlama sisteminin amacı ve stratejik hedefleri dökümante edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Raporlama sisteminin niçin kurulduğuna dair işletmenin stratejik emniyet hedeflerinin belirlenip belirlenmediğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Üst yönetim onaylı Emniyet Politikası dökümanı, emniyet hedefleri (Safety Objectives) listesi veya SMS el kitabı amaç/kapsam bölümü.",
      "sourcePage": 5
    },
    {
      "id": 4,
      "htmlKey": "fr13-zrs-2-aad01",
      "questionNo": 2,
      "questionCode": "SHGM.EYU.ZRS.2",
      "shortCode": "ZRS.2",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 4; Reg. (EU) No. 376/2014 Article 2",
      "question": "Kuruluş, ilgili mevzuat kapsamında faaliyetleri ile ilgili olan olay raporlama ile ilgili tanımları dokümante etmiş mi?",
      "atomicCriterion": "SHT-OLAY ve Reg. (EU) No. 376/2014 Madde 2'deki temel tanımlar (Kaza, Ciddi Olay, Olay vb.) kuruluş prosedürlerine hatasız aktarılmıştır",
      "auditorGuidance": "İncelenecek Husus: Kaza, ciddi olay ve olay gibi temel havacılık emniyeti tanımlarının, ulusal ve uluslararası mevzuata (SHT-OLAY / Reg. 376/2014 Madde 2) tam uyumlu olarak el kitaplarında yer aldığının teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı \"Tanımlar ve Kısaltmalar\" bölümü veya İşletme El Kitabı (OM-A) ilgili giriş sayfaları.",
      "sourcePage": 6
    },
    {
      "id": 5,
      "htmlKey": "fr13-zrs-2-aad02",
      "questionNo": 2,
      "questionCode": "SHGM.EYU.ZRS.2",
      "shortCode": "ZRS.2",
      "aadCode": "AAD02",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 4; Reg. (EU) No. 376/2014 Article 2",
      "question": "Kuruluş, ilgili mevzuat kapsamında faaliyetleri ile ilgili olan olay raporlama ile ilgili tanımları dokümante etmiş mi?",
      "atomicCriterion": "Kuruluşun faaliyet alanına (uçuş işletme, bakım, yer hizmetleri vb.) özgü spesifik olay tanımları ve örnekleri dökümante edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Kuruluşun kendi operasyonel yapısına ve yetki alanlarına göre (Uçuş İşletme, Bakım/Sürekli Uçuşa Elverişlilik, Yer Hizmetleri vb.) hangi spesifik olayların zorunlu olarak raporlanması gerektiğinin bölümsel bazda sınırlandırılması ve dökümante edilmesi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı Ekleri (Zorunlu Olay Listeleri), Departman Raporlama Prosedürleri veya Birim Esaslı Emniyet Kılavuzları.",
      "sourcePage": 7
    },
    {
      "id": 6,
      "htmlKey": "fr13-zrs-2-aad03",
      "questionNo": 2,
      "questionCode": "SHGM.EYU.ZRS.2",
      "shortCode": "ZRS.2",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 4; Reg. (EU) No. 376/2014 Article 2",
      "question": "Kuruluş, ilgili mevzuat kapsamında faaliyetleri ile ilgili olan olay raporlama ile ilgili tanımları dokümante etmiş mi?",
      "atomicCriterion": "El kitabındaki tanımlar ile raporlama formlarındaki (dijital/basılı) olay sınıflandırma seçenekleri birbirleriyle uyumludur",
      "auditorGuidance": "İncelenecek Husus: Dijital raporlama yazılımı arayüzündeki olay tipleri, hava aracı kategorileri, teknik arıza kırılımları gibi menülerin ve veri alanlarının uluslararası ADREP/ECCAIRS taksonomisi standartlarıyla birebir eşleştiğinin sistem başında teyidi.\n\nKabul Edilebilir Kanıtlar: Canlı emniyet veri tabanı/yazılım arayüz testi, sistem teknik dokümantasyonu veya ADREP taksonomi uyumluluk matrisi belgesi.",
      "sourcePage": 8
    },
    {
      "id": 7,
      "htmlKey": "fr13-zrs-3-aad01",
      "questionNo": 3,
      "questionCode": "SHGM.EYU.ZRS.3",
      "shortCode": "ZRS.3",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 2(1), Madde 5(2), Ek-1, Madde 6(1); Reg. (EU) No. 376/2014 Article 4(1); Reg. (EU) No. 2015/1018 Article 1",
      "question": "Kuruluş, havacılık emniyeti için önemli bir risk teşkil edebilecek ve zorunlu olarak raporlanması gereken olayları belirlemiş mi?",
      "atomicCriterion": "Kuruluşun zorunlu raporlama listesi, SHT-OLAY Ek-1, Reg. (EU) No. 2015/1018 Ek-1, 2, 3, 4 ve 5'teki ve SHT-18 Madde 15'teki olay kategorilerini (faaliyet alanına uygun olarak) eksiksiz içermektedir",
      "auditorGuidance": "İncelenecek Husus: Kuruluşun olay listesinin mevzuatla (Reg. 2015/1018 ekleri, SHT-OLAY Ek-1 ve SHT-18 Madde 15) eksiksiz uyumlu olduğu ve \"listede olmayan ancak emniyeti etkileyen olayların da raporlanacağına\" dair kapsayıcı beyan içerdiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı \"Raporlanacak Olaylar\" listesi ve denetim öncesi/sırası yapılan mevzuat-el kitabı karşılaştırma tablosu.",
      "sourcePage": 9
    },
    {
      "id": 8,
      "htmlKey": "fr13-zrs-3-aad02",
      "questionNo": 3,
      "questionCode": "SHGM.EYU.ZRS.3",
      "shortCode": "ZRS.3",
      "aadCode": "AAD02",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 2(1), Madde 5(2), Ek-1, Madde 6(1); Reg. (EU) No. 376/2014 Article 4(1); Reg. (EU) No. 2015/1018 Article 1",
      "question": "Kuruluş, havacılık emniyeti için önemli bir risk teşkil edebilecek ve zorunlu olarak raporlanması gereken olayları belirlemiş mi?",
      "atomicCriterion": "Kuruluş, öncelikli olayların diğer zorunlu olaylardan ayırt edilecek şekilde raporlanmasını sağlıyor",
      "auditorGuidance": "İncelenecek Husus: Öncelikli vakaların diğer rutin olaylardan ayırt edilerek (farklı bir akış, form veya süreçle) raporlandığının canlı sistemde teyidi.\n\nKabul Edilebilir Kanıtlar: Öncelikli olay statüsünde girilmiş olay bildirim formları.",
      "sourcePage": 10
    },
    {
      "id": 9,
      "htmlKey": "fr13-zrs-3-aad03",
      "questionNo": 3,
      "questionCode": "SHGM.EYU.ZRS.3",
      "shortCode": "ZRS.3",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 2(1), Madde 5(2), Ek-1, Madde 6(1); Reg. (EU) No. 376/2014 Article 4(1); Reg. (EU) No. 2015/1018 Article 1",
      "question": "Kuruluş, havacılık emniyeti için önemli bir risk teşkil edebilecek ve zorunlu olarak raporlanması gereken olayları belirlemiş mi?",
      "atomicCriterion": "Kuruluş, yurt dışında yaşanan olayları otoriteye raporluyor",
      "auditorGuidance": "İncelenecek Husus: Yurt dışında meydana gelen emniyet olaylarının merkez sisteme entegre edildiği ve otoriteye (SHGM) zamanında iletildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Yurt dışı istasyonlardan gelen örnek olay raporları, bunların SHGM bildirim logları veya \"Yurt dışı operasyonlar da raporlanır\" prosedürünün operasyonel kayıtları.",
      "sourcePage": 11
    },
    {
      "id": 10,
      "htmlKey": "fr13-zrs-3-aad04",
      "questionNo": 3,
      "questionCode": "SHGM.EYU.ZRS.3",
      "shortCode": "ZRS.3",
      "aadCode": "AAD04",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 2(1), Madde 5(2), Ek-1, Madde 6(1); Reg. (EU) No. 376/2014 Article 4(1); Reg. (EU) No. 2015/1018 Article 1",
      "question": "Kuruluş, havacılık emniyeti için önemli bir risk teşkil edebilecek ve zorunlu olarak raporlanması gereken olayları belirlemiş mi?",
      "atomicCriterion": "Kuruluş, Türk Hava Sahasındaki yabancı işleticilerin müdahil olduğu olayları otoriteye raporluyor",
      "auditorGuidance": "İncelenecek Husus: Türk hava sahasında hizmet verilen yabancı işleticilere (yabancı tescilli hava araçlarına vb.) ait emniyet olaylarının raporlanıp otoriteye bildirildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Yer hizmetleri veya bakım birimleri tarafından doldurulmuş \"Yabancı Tescilli Hava Aracı\" olay raporları ve bildirim dokümanları.",
      "sourcePage": 12
    },
    {
      "id": 11,
      "htmlKey": "fr13-zrs-3-aad05",
      "questionNo": 3,
      "questionCode": "SHGM.EYU.ZRS.3",
      "shortCode": "ZRS.3",
      "aadCode": "AAD05",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 2(1), Madde 5(2), Ek-1, Madde 6(1); Reg. (EU) No. 376/2014 Article 4(1); Reg. (EU) No. 2015/1018 Article 1",
      "question": "Kuruluş, havacılık emniyeti için önemli bir risk teşkil edebilecek ve zorunlu olarak raporlanması gereken olayları belirlemiş mi?",
      "atomicCriterion": "Raporlanması gereken olaylar, kuruluşun departmanlarına (Uçuş İşletme, Havaalanı İşletme, Balon İşletme, Yer Hizmetleri, Teknik vb.) göre sınıflandırılmış ve bu birimlerin icra ettiği faaliyetlerin terminolojisine uygun örneklerle dökümante edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Karmaşık olay raporlama listelerinin; uçuş, bakım, yer hizmetleri gibi spesifik operasyonel birimlerin terminolojisine uygun pratik örneklere dönüştürülerek dokümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Departmanlara özel hazırlanan spesifik raporlama rehberleri, örnek olay broşürleri veya personelin cep/QRH kartları.",
      "sourcePage": 13
    },
    {
      "id": 12,
      "htmlKey": "fr13-zrs-3-aad06",
      "questionNo": 3,
      "questionCode": "SHGM.EYU.ZRS.3",
      "shortCode": "ZRS.3",
      "aadCode": "AAD06",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 2(1), Madde 5(2), Ek-1, Madde 6(1); Reg. (EU) No. 376/2014 Article 4(1); Reg. (EU) No. 2015/1018 Article 1",
      "question": "Kuruluş, havacılık emniyeti için önemli bir risk teşkil edebilecek ve zorunlu olarak raporlanması gereken olayları belirlemiş mi?",
      "atomicCriterion": "İlgili personel, kendi görev alanı ile ilgili hangi olayları zorunlu olarak raporlaması gerektiği konusunda yeterli bilgiye sahiptir",
      "auditorGuidance": "İncelenecek Husus: Sahadaki operasyonel personelin (teknisyen, memur vb.), kendi alanında hangi spesifik durumların zorunlu raporlama kapsamında olduğunu teorik ve pratik düzeyde bildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Saha personeli ile yapılan örnek olay senaryolu mülakat notları ile olay kategorilerini içeren SMS eğitim ve sınav kayıtları (personel eğitimlerinde Reg. 2015/1018 kategorilerinin anlatılıp anlatılmadığı, sınav sorularında bu olay tiplerinin geçip geçmediği kontrol edilir.)",
      "sourcePage": 14
    },
    {
      "id": 13,
      "htmlKey": "fr13-zrs-4-aad01",
      "questionNo": 4,
      "questionCode": "SHGM.EYU.ZRS.4",
      "shortCode": "ZRS.4",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 5(1)",
      "question": "Kuruluş, öngörülen zorunlu olayları kuruluş tarafından kurulan sistem aracılığıyla bildirecek gerçek kişileri belirlemiş ve listelemiş mi?",
      "atomicCriterion": "Zorunlu raporlama yapması gereken personel unvanları, Reg. (EU) No. 376/2014 Madde 4(6) ve SHT-OLAY Madde 5 ile uyumlu şekilde tanımlanmıştır",
      "auditorGuidance": "İncelenecek Husus: Mevzuatta (Reg. 376/2014 Madde 4(6) ve SHT-OLAY Madde 5) belirtilen ve zorunlu raporlama yapmakla yükümlü olan operasyonel personel unvanlarının (Pilot, Teknisyen, Yer Hizmetleri vb.), işletmenin güncel organizasyon yapısına uygun ve eksiksiz şekilde dokümante edildiğinin teyidi.\n\nKuruluşun organizasyon yapısındaki değişimlerin (yeni bir departman açılması vb.) bu listeye yansıtılıp yansıtılmadığı.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı veya İşletme El Kitabı (OM-A) \"Sorumluluklar\" bölümünde yer alan Olay Raporlama Yükümlüleri / Personel Listesi.",
      "sourcePage": 15
    },
    {
      "id": 14,
      "htmlKey": "fr13-zrs-4-aad02",
      "questionNo": 4,
      "questionCode": "SHGM.EYU.ZRS.4",
      "shortCode": "ZRS.4",
      "aadCode": "AAD02",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 5(1)",
      "question": "Kuruluş, öngörülen zorunlu olayları kuruluş tarafından kurulan sistem aracılığıyla bildirecek gerçek kişileri belirlemiş ve listelemiş mi?",
      "atomicCriterion": "Belirlenen personelin olay raporlama yükümlülükleri ve sorumlulukları, ilgili personelin resmi görev tanımlarına (Job Descriptions) bir iş gerekliliği olarak eklenmiştir",
      "auditorGuidance": "İncelenecek Husus: Raporlama yapmakla yükümlü personelin, bu zorunluluğunun resmi İnsan Kaynakları görev tanımlarında (Job Descriptions) veya kontrol bir dokümanda yer alan görev tanımlarında ayrılmaz bir \"iş gerekliliği / emniyet sorumluluğu\" olarak açıkça yer aldığının teyidi.\n\nKabul Edilebilir Kanıtlar: Organizasyondaki farklı operasyonel unvanlara (örn. B1 Teknisyen, Operasyon Memuru) ait onaylı \"Görev Tanımı (JD)\" dokümanı örnekleri.",
      "sourcePage": 16
    },
    {
      "id": 15,
      "htmlKey": "fr13-zrs-4-aad03",
      "questionNo": 4,
      "questionCode": "SHGM.EYU.ZRS.4",
      "shortCode": "ZRS.4",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 5(1)",
      "question": "Kuruluş, öngörülen zorunlu olayları kuruluş tarafından kurulan sistem aracılığıyla bildirecek gerçek kişileri belirlemiş ve listelemiş mi?",
      "atomicCriterion": "Raporlama yapmakla yükümlü gerçek kişilerin, raporlama sistemine (yazılım, portal vb.) erişim yetkileri ve kullanıcı tanımları aktif durumdadır",
      "auditorGuidance": "İncelenecek Husus: El kitabında tanımlı olan zorunlu raporlama personelinin, dijital raporlama sisteminde (yazılım portalı) karşılığı olan yetkilendirmelere sahip olduğunun ve kendi şifreleriyle sisteme erişebildiğinin canlı teyidi.\n\nKabul Edilebilir Kanıtlar: Sistem üzerinden alınan \"Aktif Kullanıcı\" ve \"Yazılım Kullanıcı Yetki Matrisi\" listesi ile personelin raporlama ekranına erişebilirliğinin (giriş testi) sahadaki doğrulaması.",
      "sourcePage": 17
    },
    {
      "id": 16,
      "htmlKey": "fr13-grs-7-aad01",
      "questionNo": 5,
      "questionCode": "SHGM.EYU.GRS.7",
      "shortCode": "GRS.7",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 8; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 5(1)",
      "question": "İşletme, gönüllü raporlama sistemi kurmuş mu?",
      "atomicCriterion": "Zorunlu raporlama kapsamı dışındaki emniyet risklerinin bildirilmesine yönelik bir gönüllü raporlama sistemi tesis edilmiş ve ilgili prosedürler dökümante edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Zorunlu raporlama kapsamı dışındaki olayların bildirilmesine yönelik kurulan gönüllü raporlama sisteminin (zorunlu sistemden farkları ve işleyişi ile birlikte) dökümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabının ilgili bölümü (Genellikle Bölüm 4) veya Gönüllü Raporlama Prosedürü.",
      "sourcePage": 18
    },
    {
      "id": 17,
      "htmlKey": "fr13-grs-7-aad02",
      "questionNo": 5,
      "questionCode": "SHGM.EYU.GRS.7",
      "shortCode": "GRS.7",
      "aadCode": "AAD02",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 8; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 5(1)",
      "question": "İşletme, gönüllü raporlama sistemi kurmuş mu?",
      "atomicCriterion": "El kitabında emniyetle ilgili her türlü bilginin havacılık emniyeti için gerçek veya potansiyel bir tehlike oluşturduğunun algılanması halinde rapor edilmesi gerektiği açıklanıyor",
      "auditorGuidance": "İncelenecek Husus: Emniyetle ilgili her türlü bilginin, gerçek veya potansiyel bir tehlike oluşturduğu algılanması halinde personel tarafından rapor edilebileceği kuralının dökümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı veya Gönüllü Raporlama Prosedüründe yer alan kapsayıcı nitelikteki ilgili beyan/ifade.",
      "sourcePage": 19
    },
    {
      "id": 18,
      "htmlKey": "fr13-grs-7-aad03",
      "questionNo": 5,
      "questionCode": "SHGM.EYU.GRS.7",
      "shortCode": "GRS.7",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 8; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 5(1)",
      "question": "İşletme, gönüllü raporlama sistemi kurmuş mu?",
      "atomicCriterion": "Gönüllü raporlama kanalları (fiziksel kutu, dijital portal, e-posta vb.) personelin kolayca erişebileceği ve kimlik gizliliğinin (anonimlik) korunduğu şekilde yapılandırılmıştır",
      "auditorGuidance": "İncelenecek Husus: Gönüllü raporlama kanallarının erişilebilir olduğunun ve kimliği gizli tutma (anonimlik) işlevinin hem dijital hem de fiziksel ortamlarda fiilen çalıştığının sahada doğrulanması.\n\nKabul Edilebilir Kanıtlar: Dijital formda \"İsmimi gizli tut/İsimsiz gönder\" seçeneğinin arayüz testi, fiziksel kutu varsa sahadaki kamera kör noktası gözlemi ve gizlilik taahhütnamesi.",
      "sourcePage": 20
    },
    {
      "id": 19,
      "htmlKey": "fr13-grs-7-aad04",
      "questionNo": 5,
      "questionCode": "SHGM.EYU.GRS.7",
      "shortCode": "GRS.7",
      "aadCode": "AAD04",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 8; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 5(1)",
      "question": "İşletme, gönüllü raporlama sistemi kurmuş mu?",
      "atomicCriterion": "Gönüllü raporlamalardan elde edilen veriler analiz edilmekte ve raporu sunan kişiye (mümkünse) süreç hakkında geri bildirim sağlanmaktadır",
      "auditorGuidance": "İncelenecek Husus: Gönüllü raporlardan elde edilen verilerin analiz döngüsüne girdiği ve raporlayıcıya (anonim değilse) inceleme sonucu hakkında geri bildirim sağlandığının teyidi.\n\nKabul Edilebilir Kanıtlar: Gelen raporların işlendiği \"Gönüllü Rapor Takip Logu\", personele gönderilen otomatik kapanış bildirimleri veya e-posta geri bildirim yazışmaları.",
      "sourcePage": 21
    },
    {
      "id": 20,
      "htmlKey": "fr13-grs-7-aad05",
      "questionNo": 5,
      "questionCode": "SHGM.EYU.GRS.7",
      "shortCode": "GRS.7",
      "aadCode": "AAD05",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 8; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 5(1)",
      "question": "İşletme, gönüllü raporlama sistemi kurmuş mu?",
      "atomicCriterion": "Gönüllü raporlar sonucunda belirlenen emniyet tehlikeleri, risk yönetimi sürecine dahil edilmekte ve emniyeti artırıcı somut tedbirler alınmaktadır",
      "auditorGuidance": "İncelenecek Husus: Gönüllü raporlardan elde edilen verilerin, risk yönetimi sürecine (SRB/SAG toplantıları) taşındığı ve emniyeti artırıcı somut aksiyonlara/tedbirlere dönüştüğünün teyidi.\n\nKabul Edilebilir Kanıtlar: Son 1 yıl içinde gönüllü bir rapor sayesinde alınmış somut önlem kayıtları, Emniyet Kurulu (SAG/SRB) toplantı tutanakları, yayınlanan emniyet bültenleri veya revize edilen prosedürler.",
      "sourcePage": 22
    },
    {
      "id": 21,
      "htmlKey": "fr13-grs-8-aad01",
      "questionNo": 6,
      "questionCode": "SHGM.EYU.GRS.8",
      "shortCode": "GRS.8",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 8; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 5(6)",
      "question": "Kuruluş, gönüllü raporlama kapsamında toplanan ve mevcut veya potansiyel bir havacılık emniyeti riski içerebilecek olayların ayrıntılarını ve emniyetle ilgili diğer bilgileri Genel Müdürlüğe zamanında bildirmek için bir sistem kurmuş mu?",
      "atomicCriterion": "Gönüllü raporlama kanalıyla toplanan ve emniyet riski taşıdığı değerlendirilen bilgilerin Genel Müdürlüğe (SHGM) iletilmesine ilişkin iş akışı dökümante edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Gönüllü raporlama kanalıyla toplanan ve işletme tarafından emniyet riski taşıdığı değerlendirilen bilgilerin SHGM'ye \"zamanında\" (net bir süre sınırı tanımlanarak) iletilmesini sağlayan iş akışının dokümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı veya Olay Raporlama Prosedüründe yer alan, SHGM'ye gönüllü bildirim akışını ve tanımlı zaman kriterlerini (Örn: analiz tamamlandıktan sonra 30 gün içinde vb.) gösteren maddeler.",
      "sourcePage": 23
    },
    {
      "id": 22,
      "htmlKey": "fr13-grs-8-aad02",
      "questionNo": 6,
      "questionCode": "SHGM.EYU.GRS.8",
      "shortCode": "GRS.8",
      "aadCode": "AAD02",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 8; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 5(6)",
      "question": "Kuruluş, gönüllü raporlama kapsamında toplanan ve mevcut veya potansiyel bir havacılık emniyeti riski içerebilecek olayların ayrıntılarını ve emniyetle ilgili diğer bilgileri Genel Müdürlüğe zamanında bildirmek için bir sistem kurmuş mu?",
      "atomicCriterion": "Gönüllü raporların hangilerinin otoriteye bildirileceğine dair risk bazlı değerlendirme kriterleri (eşik değerler, risk matrisi skorları vb.) belirlenmiştir",
      "auditorGuidance": "İncelenecek Husus: Gelen gönüllü raporlardan hangilerinin \"emniyet riski teşkil ettiği\" için otoriteye bildirileceğini belirleyen risk bazlı süzgeç mekanizmasının (eşik değerler) ve karar verici makamın (Örn: Emniyet Müdürü, SAG vb.) net olarak tanımlandığının teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı bildirim karar süreçleri dökümantasyonu, Risk Değerlendirme/Bildirim Karar Matrisi veya Eşik Değer tabloları.",
      "sourcePage": 24
    },
    {
      "id": 23,
      "htmlKey": "fr13-grs-8-aad03",
      "questionNo": 6,
      "questionCode": "SHGM.EYU.GRS.8",
      "shortCode": "GRS.8",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 8; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 5(6)",
      "question": "Kuruluş, gönüllü raporlama kapsamında toplanan ve mevcut veya potansiyel bir havacılık emniyeti riski içerebilecek olayların ayrıntılarını ve emniyetle ilgili diğer bilgileri Genel Müdürlüğe zamanında bildirmek için bir sistem kurmuş mu?",
      "atomicCriterion": "Emniyet riski içeren gönüllü raporların otoriteye bildirimine ilişkin kayıtlar mevcuttur ve bildirimlerin belirlenen takvime uygun yapıldığı doğrulanmaktadır",
      "auditorGuidance": "İncelenecek Husus: Emniyet riski içeren gönüllü raporların kurum içi kayıtlarla örtüştüğünün ve belirlenen takvime uygun olarak (anonimleştirilerek) otoriteye bildirildiğinin geçmişe dönük kayıtlar üzerinden doğrulanması.\n\nKabul Edilebilir Kanıtlar: Kurum içi \"Gönüllü Rapor Listesi\" ile SHGM'ye gönderilen bildirimlerin karşılaştırmalı analizi; SHGM'ye iletilen resmi yazılar veya sistem üzerinden gönderilen dijital form logları.",
      "sourcePage": 25
    },
    {
      "id": 24,
      "htmlKey": "fr13-kcob-9-aad01",
      "questionNo": 7,
      "questionCode": "SHGM.EYU.KCOB.9",
      "shortCode": "KCOB.9",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 5(1)",
      "question": "Kuruluş, kaza ve ciddi olayları Ulaşım Emniyeti İnceleme Merkezi Başkanlığına ve bilgi amaçlı olarak Genel Müdürlüğe iletiyor mu?",
      "atomicCriterion": "HKY-13 Madde 9(2) gereği, kaza ve ciddi olayların UEİMB ve SHGM’ye bildirilmesine ilişkin özel bir acil durum bildirim akışı dökümante edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Kaza ve ciddi olayların, ilgili mevzuat (HKY-13) gereği Ulaşım Emniyeti İnceleme Merkezi Başkanlığına (UEİMB) ve bilgi amaçlı SHGM'ye hangi kanal/yöntemle iletileceğini gösteren acil durum bildirim akışının güncel kurum isimleriyle dökümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı veya Acil Durum Müdahale Planı (ERP) bildirim şeması, Olay Raporlama Prosedüründeki ilgili acil durum bildirim maddeleri.",
      "sourcePage": 26
    },
    {
      "id": 25,
      "htmlKey": "fr13-kcob-9-aad02",
      "questionNo": 7,
      "questionCode": "SHGM.EYU.KCOB.9",
      "shortCode": "KCOB.9",
      "aadCode": "AAD02",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 5(1)",
      "question": "Kuruluş, kaza ve ciddi olayları Ulaşım Emniyeti İnceleme Merkezi Başkanlığına ve bilgi amaçlı olarak Genel Müdürlüğe iletiyor mu?",
      "atomicCriterion": "UEİM ve SHGM’nin kaza bildirim birimlerine ait güncel iletişim bilgileri (telefon, faks, 7/24 ulaşılabilecek numaralar) ilgili birimlerin erişimine sunulmuştur",
      "auditorGuidance": "İncelenecek Husus: UEİMB ve SHGM'nin kaza/ciddi olay acil bildirim hatlarına ait güncel iletişim bilgilerinin (7/24 telefon, faks vb.) ilgili operasyonel birimlerde (OCC, uçuş işletme, teknik nöbetçi ofisleri) anında erişilebilir durumda olduğunun sahada doğrulanması.\n\nKabul Edilebilir Kanıtlar: İlgili operasyon merkezlerinde/nöbetçi ofislerindeki fiziksel veya dijital \"Acil Durum İletişim Listesi\", sahada personelin erişimindeki acil durum bilgi kartları (QRH vb.).",
      "sourcePage": 27
    },
    {
      "id": 26,
      "htmlKey": "fr13-kcob-9-aad03",
      "questionNo": 7,
      "questionCode": "SHGM.EYU.KCOB.9",
      "shortCode": "KCOB.9",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 5(1)",
      "question": "Kuruluş, kaza ve ciddi olayları Ulaşım Emniyeti İnceleme Merkezi Başkanlığına ve bilgi amaçlı olarak Genel Müdürlüğe iletiyor mu?",
      "atomicCriterion": "Varsa, meydana gelen kaza ve ciddi olaylara ilişkin bildirimlerin yasal süreler ve yöntemler dahilinde UEİMB ve SHGM’ye iletildiğine dair kanıtlar mevcuttur",
      "auditorGuidance": "İncelenecek Husus: Gerçekleşmiş kaza/ciddi olaylar için ilk bildirimlerin yasal süre ve yöntemlerle yapıldığının kayıtlar üzerinden; veya geçmişte olay yaşanmamışsa bildirim sisteminin çalışabilirliğinin tatbikatlarla (masa başı vb.) test edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Meydana gelmiş vakalara ait tarih/saat damgalı \"Kaza/Ciddi Olay İlk Bildirim Formu\" gönderim teyitleri (sistem logu, faks/e-posta iletim raporu) veya olay yaşanmamış işletmeler için periyodik ERP masa başı tatbikat (drill) raporları.",
      "sourcePage": 28
    },
    {
      "id": 27,
      "htmlKey": "fr13-bts-10-aad01",
      "questionNo": 8,
      "questionCode": "SHGM.EYU.BTS.10",
      "shortCode": "BTS.10",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 1; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(1)",
      "question": "Kuruluş, zorunlu ve gönüllü olarak raporlanan olayların ayrıntılarının toplanması, değerlendirilmesi, işlenmesi, analizi ve saklanmasıyla bağımsız olarak ilgilenecek bir veya daha fazla kişi belirlemiş mi?",
      "atomicCriterion": "Olay raporlarını işlemek, analiz etmek ve saklamak üzere görevlendirilmiş bağımsız bir kişi (Emniyet Müdürü/Sorumlusu) veya birim (Emniyet Birimi) tanımlanmıştır",
      "auditorGuidance": "İncelenecek Husus: Olay raporlarını işlemek, analiz etmek ve saklamak üzere görevlendirilen emniyet personelinin/biriminin dokümante edilmiş organizasyon yapısı içinde (doğrudan Sorumlu Müdüre / Accountable Manager'a bağlı olacak şekilde) resmi olarak tanımlandığının teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı \"Sorumluluklar\" bölümü, emniyet biriminin en üst yöneticiye doğrudan bağlılığını gösteren Organizasyon Şeması ve ilgili personelin resmi görevlendirme/atama yazısı.",
      "sourcePage": 29
    },
    {
      "id": 28,
      "htmlKey": "fr13-bts-10-aad02",
      "questionNo": 8,
      "questionCode": "SHGM.EYU.BTS.10",
      "shortCode": "BTS.10",
      "aadCode": "AAD02",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 1; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(1)",
      "question": "Kuruluş, zorunlu ve gönüllü olarak raporlanan olayların ayrıntılarının toplanması, değerlendirilmesi, işlenmesi, analizi ve saklanmasıyla bağımsız olarak ilgilenecek bir veya daha fazla kişi belirlemiş mi?",
      "atomicCriterion": "Olay raporlarını analiz eden kişi veya birimin, raporlanan operasyonel süreçlerden bağımsızlığı ve tarafsızlığı (çıkar çatışması olmaması) güvence altına alınmıştır",
      "auditorGuidance": "İncelenecek Husus: Analiz yapan kişi veya birimin, raporlanan operasyonel süreçlerden (Örn: Uçuş İşletme, Bakım) bağımsız olduğunun ve operasyonel baskı/çıkar çatışması altında kalmadan doğrudan üst yönetime rapor verebildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Emniyet Müdürü/Sorumlusu ile yapılan operasyonel bağımsızlık (reporting line) mülakat notları ve karar alma bağımsızlığını gösteren Emniyet Kurulu (SRB) toplantı tutanakları.",
      "sourcePage": 30
    },
    {
      "id": 29,
      "htmlKey": "fr13-bts-10-aad03",
      "questionNo": 8,
      "questionCode": "SHGM.EYU.BTS.10",
      "shortCode": "BTS.10",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 1; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(1)",
      "question": "Kuruluş, zorunlu ve gönüllü olarak raporlanan olayların ayrıntılarının toplanması, değerlendirilmesi, işlenmesi, analizi ve saklanmasıyla bağımsız olarak ilgilenecek bir veya daha fazla kişi belirlemiş mi?",
      "atomicCriterion": "Olay raporlarının işlenmesi, değerlendirilmesi ve analizinden sorumlu personelin, kuruluş tarafından tanımlanmış emniyet yönetimi yetkinlik kriterlerine ve eğitim gerekliliklerine uygunluğu sağlanmaktadır",
      "auditorGuidance": "İncelenecek Husus: Olay raporlarının işlenmesi ve analizinden sorumlu personelin, kuruluş tarafından tanımlanmış emniyet yönetimi yetkinlik ve eğitim gerekliliklerini karşıladığının ve fiili analizlerin de bu standartta yapıldığının teyidi.\n\nKabul Edilebilir Kanıtlar: Emniyet personeli Yetkinlik Matrisi (Competency Matrix), ilgili SMS/analiz eğitimlerine ait başarı sertifikaları ve bu personel tarafından hazırlanmış metodolojiye uygun (teknik doğruluğu yüksek) örnek olay analiz raporları.",
      "sourcePage": 31
    },
    {
      "id": 30,
      "htmlKey": "fr13-bts-11-aad01",
      "questionNo": 9,
      "questionCode": "SHGM.EYU.BTS.11",
      "shortCode": "BTS.11",
      "aadCode": "AAD01",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 1, Madde 6; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(5)",
      "question": "Kuruluş, zorunlu ve gönüllü olarak raporlanan olayları saklıyor mu?",
      "atomicCriterion": "Olay verilerinin sistematik ve güvenli bir şekilde saklanması için ulusal ve uluslararası standartlarla (ADREP) uyumlu bir veri tabanı (dijital veya fiziksel) tesis edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Olay verilerinin basit tablolar (Excel vb.) yerine uluslararası emniyet standartlarına (ADREP) uygun şekilde sınıflandırma yapabilen ve otoriteye uyumlu (örn. .zip/ECCAIRS, e5x formatında) veri aktarımı sağlayabilen güvenli bir veri tabanında (dijital veya kontrollü fiziksel arşiv) tutulduğunun teyidi.\n\nKabul Edilebilir Kanıtlar: Emniyet yazılımı canlı arayüz testi, sistem teknik spesifikasyon dokümanı ve otorite sistemine aktarılabilir örnek veri çıktı/aktarım dosyası.",
      "sourcePage": 32
    },
    {
      "id": 31,
      "htmlKey": "fr13-bts-11-aad02",
      "questionNo": 9,
      "questionCode": "SHGM.EYU.BTS.11",
      "shortCode": "BTS.11",
      "aadCode": "AAD02",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 1, Madde 6; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(5)",
      "question": "Kuruluş, zorunlu ve gönüllü olarak raporlanan olayları saklıyor mu?",
      "atomicCriterion": "Verilerin saklanma süreleri (retention periods), mevzuat gerekliliklerini ve emniyet analizi ihtiyaçlarını karşılayacak şekilde dökümante edilmiş ve uygulanmaktadır",
      "auditorGuidance": "İncelenecek Husus: Olay verilerinin emniyet analizi ve mevzuat gerekliliklerine uygun olarak asgari ne kadar süre (retention period) saklanacağının net bir şekilde belirlendiğinin ve geçmiş verilere hala ulaşılabildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı veya Veri Yönetim Prosedüründe yer alan Veri Saklama Politikası (örn: asgari X yıl), geçmiş yıllara ait raporların erişilebilirliğini gösteren sistem arşiv kayıtları ve (varsa) arşiv imha tutanakları.",
      "sourcePage": 33
    },
    {
      "id": 32,
      "htmlKey": "fr13-bts-11-aad03",
      "questionNo": 9,
      "questionCode": "SHGM.EYU.BTS.11",
      "shortCode": "BTS.11",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 1, Madde 6; TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(5)",
      "question": "Kuruluş, zorunlu ve gönüllü olarak raporlanan olayları saklıyor mu?",
      "atomicCriterion": "Emniyet verilerinin kaybına veya yetkisiz değiştirilmesine karşı düzenli yedekleme (back-up) ve siber güvenlik önlemleri alınmıştır",
      "auditorGuidance": "İncelenecek Husus: Emniyet verilerinin kaybına veya manipülasyonuna karşı veri tabanının düzenli olarak farklı bir lokasyona/buluta yedeklendiğinin (back-up) ve yetkisiz değişikliklere karşı sistemsel erişim izlerinin tutulduğunun doğrulanması.\n\nKabul Edilebilir Kanıtlar: BT (Bilgi Teknolojileri) departmanından alınacak sistem yedekleme (back-up) logları, sistem erişim yetki matrisi ve kullanıcı işlem (giriş/değiştirme) kayıtları.",
      "sourcePage": 34
    },
    {
      "id": 33,
      "htmlKey": "fr13-orki-12-aad01",
      "questionNo": 10,
      "questionCode": "SHGM.EYU.ORKİ.12",
      "shortCode": "ORKİ.12",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "SHT-OLAY Madde 5(2); Reg. (EU) No. 376/2014 Article 7(1)",
      "question": "Olay raporları, SHGM bildirim formlarında listelenen bilgileri içeriyor mu?",
      "atomicCriterion": "Olay raporlama formları (dijital veya basılı), Reg. (EU) No. 376/2014 Ek-1’de ve SHT-OLAY’da belirtilen zorunlu veri alanlarını (olay tarihi, konumu, olay tipi, hava aracı tescil işareti vb.) eksiksiz içerecek şekilde tasarlanmıştır",
      "auditorGuidance": "İncelenecek Husus: Olay raporlama formlarının (dijital/basılı), mevzuatta (Reg. 376/2014 Ek-1, SHT-OLAY) belirtilen zorunlu veri alanlarını (tarih, konum, olay tipi vb.) eksiksiz içerdiği ve dijital sistemlerde bu alanların \"boş geçilemez\" (mandatory) olarak ayarlandığının teyidi.\n\nKabul Edilebilir Kanıtlar: Boş olay rapor formu örneği, yazılım arayüzü ekran görüntüsü ve formun mevzuat ekindeki zorunlu alanlarla karşılaştırmalı analizi.",
      "sourcePage": 35
    },
    {
      "id": 34,
      "htmlKey": "fr13-orki-12-aad02",
      "questionNo": 10,
      "questionCode": "SHGM.EYU.ORKİ.12",
      "shortCode": "ORKİ.12",
      "aadCode": "AAD02",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 5(2); Reg. (EU) No. 376/2014 Article 7(1)",
      "question": "Olay raporları, SHGM bildirim formlarında listelenen bilgileri içeriyor mu?",
      "atomicCriterion": "Meydana gelen olaylara ilişkin doldurulan raporlarda, zorunlu veri alanlarının doğru, tutarlı ve analiz edilebilir şekilde doldurulduğu doğrulanmaktadır",
      "auditorGuidance": "İncelenecek Husus: Doldurulan olay raporlarındaki zorunlu alanların \"Bilinmiyor/NA\" gibi kaçamak ifadelerle geçiştirilmediğinin, verilerin doğru/tutarlı olduğunun ve serbest metin (narrative) kısımlarının kök neden analizine imkan verecek detayda doldurulduğunun teyidi.\n\nKabul Edilebilir Kanıtlar: Örnekleme (Sampling) yöntemiyle sistemden rastgele seçilen, tamamlanmış ve otoriteye gönderilmiş 5 adet örnek olay raporu.",
      "sourcePage": 36
    },
    {
      "id": 35,
      "htmlKey": "fr13-orki-12-aad03",
      "questionNo": 10,
      "questionCode": "SHGM.EYU.ORKİ.12",
      "shortCode": "ORKİ.12",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 5(2); Reg. (EU) No. 376/2014 Article 7(1)",
      "question": "Olay raporları, SHGM bildirim formlarında listelenen bilgileri içeriyor mu?",
      "atomicCriterion": "Raporlama sisteminde kullanılan terimler ve olay sınıflandırmaları, ADREP taksonomisi ile uyumludur",
      "auditorGuidance": "İncelenecek Husus: Raporlama yazılımındaki açılır menü terimlerinin (Olay kategorisi, faz vb.) ICAO ADREP taksonomisi ile örtüştüğünün ve serbest metin (narrative) açıklamalarıyla sisteme girilen ADREP kodlamalarının birebir uyumlu olduğunun canlı olarak doğrulanması.\n\nKabul Edilebilir Kanıtlar: Yazılım veri sözlüğü (Data Dictionary) / ADREP uyumluluk beyanı ve sistem üzerinden seçilen son 5 raporun (örn: pistten çıkma, kuş çarpması) canlı ADREP kodlama uyumu testi.",
      "sourcePage": 37
    },
    {
      "id": 36,
      "htmlKey": "fr13-orki-12-aad04",
      "questionNo": 10,
      "questionCode": "SHGM.EYU.ORKİ.12",
      "shortCode": "ORKİ.12",
      "aadCode": "AAD04",
      "auditType": "Yerinde",
      "reference": "SHT-OLAY Madde 5(2); Reg. (EU) No. 376/2014 Article 7(1)",
      "question": "Olay raporları, SHGM bildirim formlarında listelenen bilgileri içeriyor mu?",
      "atomicCriterion": "ADREP kodlamalarının kalite kontrolü periyodik olarak yapılmaktadır",
      "auditorGuidance": "İncelenecek Husus: Sisteme girilen olaylardaki ADREP kodlamalarının (yanlış taksonomi seçimi vb.) doğruluğunun ve veri kalitesinin emniyet birimi tarafından periyodik olarak denetlendiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Emniyet birimi tarafından yürütülen periyodik (aylık/çeyreklik) ADREP veri kalitesi gözden geçirme raporları, kontrol listeleri (checklist), düzeltme logları veya iç denetim kayıtları.",
      "sourcePage": 38
    },
    {
      "id": 37,
      "htmlKey": "fr13-oai-t-13-aad01",
      "questionNo": 11,
      "questionCode": "SHGM.EYU.OAİT.13",
      "shortCode": "OAİT.13",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 13(1), Article 13(2), Article 13(3)",
      "question": "Kuruluş, tanımlanan olaylar veya olay grupları ile ilişkili emniyet tehlikelerini belirlemek amacıyla toplanan olayları analiz ederek havacılık emniyetini iyileştirmek için gereken uygun düzeltici veya önleyici eylemleri belirliyor mu?",
      "atomicCriterion": "Olayların analizi, tehlike tanımlama ve risk değerlendirme süreçlerini içeren sistematik bir yöntem (prosedür) dökümante edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Olayların analizi, tehlike tanımlama ve risk değerlendirme süreçleri için; metodoloji (Örn: Reason, Bow-Tie, ARMS), sorumlular ve zaman çizelgelerini içeren sistematik bir kural setinin dokümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı \"Analiz/Risk Yönetimi\" Bölümü veya Olay İnceleme ve Analiz Prosedürü.",
      "sourcePage": 39
    },
    {
      "id": 38,
      "htmlKey": "fr13-oai-t-13-aad02",
      "questionNo": 11,
      "questionCode": "SHGM.EYU.OAİT.13",
      "shortCode": "OAİT.13",
      "aadCode": "AAD02",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 13(1), Article 13(2), Article 13(3)",
      "question": "Kuruluş, tanımlanan olaylar veya olay grupları ile ilişkili emniyet tehlikelerini belirlemek amacıyla toplanan olayları analiz ederek havacılık emniyetini iyileştirmek için gereken uygun düzeltici veya önleyici eylemleri belirliyor mu?",
      "atomicCriterion": "Her bir olay raporu, potansiyel emniyet riski (olasılık ve şiddet) açısından sistematik olarak değerlendirilmekte ve bir risk seviyesiyle sınıflandırılmaktadır",
      "auditorGuidance": "İncelenecek Husus: Olayların potansiyel riskine (olasılık/şiddet) göre sınıflandırıldığının ve risk skoruna göre (Düşük/Orta/Yüksek) doğru aksiyon türlerinin (Detaylı İnceleme, Standart Değerlendirme veya Trend Takibi) canlı sistemde tutarlı bir şekilde tetiklendiğinin doğrulanması.\n\nKabul Edilebilir Kanıtlar: Aksiyon/Karar matrisi, risk seviyesine göre başlatılmış örnek \"Olay İnceleme Raporları\" (Investigation), \"Emniyet Değerlendirme Formları\" (Assessment) ve istatistiki veri kırılım tabloları.",
      "sourcePage": 40
    },
    {
      "id": 39,
      "htmlKey": "fr13-oai-t-13-aad03",
      "questionNo": 11,
      "questionCode": "SHGM.EYU.OAİT.13",
      "shortCode": "OAİT.13",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 13(1), Article 13(2), Article 13(3)",
      "question": "Kuruluş, tanımlanan olaylar veya olay grupları ile ilişkili emniyet tehlikelerini belirlemek amacıyla toplanan olayları analiz ederek havacılık emniyetini iyileştirmek için gereken uygun düzeltici veya önleyici eylemleri belirliyor mu?",
      "atomicCriterion": "Analizler sonucunda belirlenen düzeltici ve önleyici faaliyetler, tanımlanan termin süreleri ve sorumlu atamaları dahilinde hayata geçirilmektedir",
      "auditorGuidance": "İncelenecek Husus: Analizler sonucu belirlenen düzeltici ve önleyici faaliyetlerin (DÖF), soyut ifadeler (\"eğitim verildi\" vb.) yerine somut aksiyonlarla (\"prosedür değişti\", \"ekipman yenilendi\" vb.), belirlenen termin süreleri ve sorumlular dahilinde hayata geçirildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Kapatılmış DÖF formları, faaliyet takip çizelgeleri (log) ve aksiyon sonucu değiştirilen operasyonel prosedür nüshaları.",
      "sourcePage": 41
    },
    {
      "id": 40,
      "htmlKey": "fr13-oai-t-13-aad04",
      "questionNo": 11,
      "questionCode": "SHGM.EYU.OAİT.13",
      "shortCode": "OAİT.13",
      "aadCode": "AAD04",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 13(1), Article 13(2), Article 13(3)",
      "question": "Kuruluş, tanımlanan olaylar veya olay grupları ile ilişkili emniyet tehlikelerini belirlemek amacıyla toplanan olayları analiz ederek havacılık emniyetini iyileştirmek için gereken uygun düzeltici veya önleyici eylemleri belirliyor mu?",
      "atomicCriterion": "Uygulanan düzeltici faaliyetlerin emniyet riskini azaltmadaki etkinliğini izlemek ve ölçmek için bir takip süreci işletilmektedir",
      "auditorGuidance": "İncelenecek Husus: Uygulanan düzeltici faaliyetlerin emniyet riskini azaltmada gerçekten işe yarayıp yaramadığını (etkinliğini) ölçmek için bir takip döngüsünün işletildiğinin ve tekrarlayan olayların izlendiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: DÖF Etkinlik Takip/Değerlendirme Formları ve (varsa) emniyet denetim (Audit) raporları.",
      "sourcePage": 42
    },
    {
      "id": 41,
      "htmlKey": "fr13-oai-t-13-aad05",
      "questionNo": 11,
      "questionCode": "SHGM.EYU.OAİT.13",
      "shortCode": "OAİT.13",
      "aadCode": "AAD05",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 13(1), Article 13(2), Article 13(3)",
      "question": "Kuruluş, tanımlanan olaylar veya olay grupları ile ilişkili emniyet tehlikelerini belirlemek amacıyla toplanan olayları analiz ederek havacılık emniyetini iyileştirmek için gereken uygun düzeltici veya önleyici eylemleri belirliyor mu?",
      "atomicCriterion": "Olay raporları üzerinden periyodik trend analizleri yapılmakta ve elde edilen sonuçlar emniyet performansı göstergeleri (SPI) ile ilişkilendirilerek üst yönetime sunulmaktadır",
      "auditorGuidance": "İncelenecek Husus: Olay verilerinden periyodik trend analizleri (aylık/yıllık) yapıldığı, tekrarlayan olaylara karşı proaktif çalışmalar yürütüldüğü ve sonuçların Emniyet Performans Göstergeleri (SPI) ile eşleştirilerek üst yönetim toplantılarında karar destek unsuru olarak kullanıldığının teyidi.\n\nKabul Edilebilir Kanıtlar: Trend/Pareto grafikleri içeren Emniyet Performans Raporları, tekrarlayan olaylara yönelik özel emniyet çalışmaları (Safety Studies) ve SRB/SAG toplantı tutanakları.",
      "sourcePage": 43
    },
    {
      "id": 42,
      "htmlKey": "fr13-oai-t-13-aad06",
      "questionNo": 11,
      "questionCode": "SHGM.EYU.OAİT.13",
      "shortCode": "OAİT.13",
      "aadCode": "AAD06",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 13(1), Article 13(2), Article 13(3)",
      "question": "Kuruluş, tanımlanan olaylar veya olay grupları ile ilişkili emniyet tehlikelerini belirlemek amacıyla toplanan olayları analiz ederek havacılık emniyetini iyileştirmek için gereken uygun düzeltici veya önleyici eylemleri belirliyor mu?",
      "atomicCriterion": "Zorunlu raporlama kapsamında toplanan olayların analiz/inceleme sonuçları ve alınan düzeltici faaliyetler, emniyeti ve gizliliği olumsuz etkilemeyecek ölçüde, raporu sunan kişiye veya ilgili operasyonel birimlere geri bildirilmektedir",
      "auditorGuidance": "İncelenecek Husus: İncelemesi tamamlanan zorunlu olay raporlarının sonuçları ve alınan aksiyonlar hakkında, emniyeti ve gizliliği ihlal etmeyecek şekilde raporlayıcı personele veya ilgili departmanlara geri bildirim sağlandığının teyidi.\n\nKabul Edilebilir Kanıtlar: Sistem üzerinden personele giden otomatik kapanış e-postaları, emniyet biriminin bilgilendirme yazışmaları veya olaydan çıkarılan derslerin (lessons learned) dağıtım kayıtları.",
      "sourcePage": 44
    },
    {
      "id": 43,
      "htmlKey": "fr13-bguk-15-aad01",
      "questionNo": 12,
      "questionCode": "SHGM.EYU.BGUK.15",
      "shortCode": "BGUK.15",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 6(1), Article 15(1), Article 16(2)",
      "question": "Kuruluş, olay ayrıntılarının gizliliğini uygun şekilde sağlamak için gerekli tedbirleri uyguluyor mu?",
      "atomicCriterion": "Kişisel veriler, yalnızca ilgili mevzuat amaçları (SHT-OLAY/Reg. 376) doğrultusunda, \"bilmesi gereken\" prensibiyle ve gerekli olduğu ölçüde işlenmektedir",
      "auditorGuidance": "İncelenecek Husus: Kişisel verilerin emniyet analizi dışında (pazarlama, İK, idari yaptırım) kullanılmayacağına dair yasal \"amaç sınırlaması\" taahhüdünün ve olay raporlarını anonimleştirme iş akışının dokümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: KVKK uyum dokümanları, SMS El Kitabı Veri Koruma/Gizlilik maddeleri ve kimlik maskeleme süreçlerini tanımlayan \"Olay Raporları Anonimleştirme Prosedürü\".",
      "sourcePage": 45
    },
    {
      "id": 44,
      "htmlKey": "fr13-bguk-15-aad02",
      "questionNo": 12,
      "questionCode": "SHGM.EYU.BGUK.15",
      "shortCode": "BGUK.15",
      "aadCode": "AAD02",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 6(1), Article 15(1), Article 16(2)",
      "question": "Kuruluş, olay ayrıntılarının gizliliğini uygun şekilde sağlamak için gerekli tedbirleri uyguluyor mu?",
      "atomicCriterion": "Raporlama yapan personelin ve olayda adı geçen üçüncü kişilerin kimlik bilgilerinin (isim, sicil, iletişim vb.) sistem üzerinde gizlenmesi/maskelenmesi sağlanmaktadır",
      "auditorGuidance": "İncelenecek Husus: Raporlayan personelin ve üçüncü kişilerin kimlik bilgilerinin (isim, sicil vb.), sistem üzerinde ve diğer departmanlara (uçuş işletme, bakım vb.) gönderilen çıktılarda fiilen maskelendiğinin canlı sistemde doğrulanması.\n\nKabul Edilebilir Kanıtlar: İsimleri maskelenmiş/kodlanmış örnek olay analiz raporu çıktıları ve emniyet yazılımının anonimleştirme arayüzünün (otomatik maskeleme) canlı ekran testi.",
      "sourcePage": 46
    },
    {
      "id": 45,
      "htmlKey": "fr13-bguk-15-aad03",
      "questionNo": 12,
      "questionCode": "SHGM.EYU.BGUK.15",
      "shortCode": "BGUK.15",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 6(1), Article 15(1), Article 16(2)",
      "question": "Kuruluş, olay ayrıntılarının gizliliğini uygun şekilde sağlamak için gerekli tedbirleri uyguluyor mu?",
      "atomicCriterion": "Olay ayrıntılarına ve kişisel verilere erişim, sadece emniyet birimi personeli ile sınırlandırılmış; diğer personelin erişimi kesinlikle gerekli durumlarla kısıtlanmıştır",
      "auditorGuidance": "İncelenecek Husus: Olay veri tabanına ve gizli bilgilere erişimin (\"bilmesi gereken\" prensibiyle) sadece emniyet birimi personeli ile sınırlandırıldığının ve yetkisiz erişimlerin log kayıtlarıyla izlendiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Bilgi İşlem (IT) onaylı Kullanıcı Yetki Matrisi (User Access Matrix) ve sisteme/veri tabanına kimlerin eriştiğini gösteren Sistem Erişim Log Raporları.",
      "sourcePage": 47
    },
    {
      "id": 46,
      "htmlKey": "fr13-bguk-15-aad04",
      "questionNo": 12,
      "questionCode": "SHGM.EYU.BGUK.15",
      "shortCode": "BGUK.15",
      "aadCode": "AAD04",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; ICAO Doküman 9859; Reg. (EU) No. 376/2014 Article 6(1), Article 15(1), Article 16(2)",
      "question": "Kuruluş, olay ayrıntılarının gizliliğini uygun şekilde sağlamak için gerekli tedbirleri uyguluyor mu?",
      "atomicCriterion": "Emniyet verilerinin saklandığı sunucular ve fiziksel arşivler, yetkisiz erişime ve veri sızıntısına karşı teknik ve idari tedbirlerle korunmaktadır",
      "auditorGuidance": "İncelenecek Husus: Emniyet verilerinin barındırıldığı dijital sunucuların siber güvenlik/şifreleme yöntemleriyle, fiziksel arşivlerin (basılı raporların) ise kilitli ve erişimi kısıtlı alanlarla korunduğunun sahada teyidi.\n\nKabul Edilebilir Kanıtlar: Dijital güvenlik için BT Güvenlik sertifikaları/altyapı belgeleri (ISO 27001 vb.) ve kilitli fiziksel arşiv odası/dolabı saha gözlemi.",
      "sourcePage": 48
    },
    {
      "id": 47,
      "htmlKey": "fr13-bguk-16-aad01",
      "questionNo": 13,
      "questionCode": "SHGM.EYU.BGUK.16",
      "shortCode": "BGUK.16",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(1), Article 15(2)",
      "question": "Bilgilerin suç veya sorumluluk atfetmek için ya da emniyet dışında başka bir amaçla kullanılmaması sağlanıyor mu?",
      "atomicCriterion": "Üst yönetim tarafından imzalanmış; ağır ihmal, kasıt veya yasa dışı eylemler hariç, emniyet raporlarının personel aleyhine disiplin veya ceza süreçlerinde kullanılmayacağını taahhüt eden bir \"Adil Kültür Politikası\" mevcuttur",
      "auditorGuidance": "İncelenecek Husus: Ağır ihmal, kasıt veya yasa dışı eylemler hariç olmak üzere, emniyet raporlarının personel aleyhine disiplin veya ceza süreçlerinde kullanılmayacağını (cezalandırmama garantisini) taahhüt eden politikanın mevcudiyeti ve üst yönetim tarafından onaylanmış olduğunun teyidi.\n\nKabul Edilebilir Kanıtlar: Güncel tarihli ve Sorumlu Müdür (Accountable Manager) tarafından imzalanmış \"Adil Kültür Deklarasyonu (Just Culture Policy)\" veya SMS El Kitabının ilgili taahhüt bölümü.",
      "sourcePage": 49
    },
    {
      "id": 48,
      "htmlKey": "fr13-bguk-16-aad02",
      "questionNo": 13,
      "questionCode": "SHGM.EYU.BGUK.16",
      "shortCode": "BGUK.16",
      "aadCode": "AAD02",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(1), Article 15(2)",
      "question": "Bilgilerin suç veya sorumluluk atfetmek için ya da emniyet dışında başka bir amaçla kullanılmaması sağlanıyor mu?",
      "atomicCriterion": "Kuruluşun disiplin kurulu kayıtları ve personel dosyaları incelendiğinde, emniyet raporlarına konu olan olayların (kasıt/ihmal hariç) bir yaptırım eylemine temel teşkil etmediği doğrulanmaktadır",
      "auditorGuidance": "İncelenecek Husus: Emniyet raporlarına konu olan olayların (kasıt/ihmal halleri hariç) personele yönelik bir yaptırım/disiplin eylemine temel teşkil etmediğinin geçmiş kayıtlar üzerinden doğrulanması ve disiplin süreçlerini yürütenlerin raporlara erişiminin kısıtlı olduğunun teyidi.\n\nKabul Edilebilir Kanıtlar: Son 1 yıla ait Disiplin Kurulu Karar Defteri/Logu ile emniyet raporlarının karşılaştırmalı analizi, personel özlük dosyası örneklemesi ve İK birimi ile yapılan mülakat notları.",
      "sourcePage": 50
    },
    {
      "id": 49,
      "htmlKey": "fr13-bguk-16-aad03",
      "questionNo": 13,
      "questionCode": "SHGM.EYU.BGUK.16",
      "shortCode": "BGUK.16",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5; Reg. (EU) No. 376/2014 Article 6(1), Article 15(2)",
      "question": "Bilgilerin suç veya sorumluluk atfetmek için ya da emniyet dışında başka bir amaçla kullanılmaması sağlanıyor mu?",
      "atomicCriterion": "Emniyet raporlarından elde edilen verilerin; ticari, idari, performans değerlendirme veya sorumluluk atfetme gibi emniyet dışı amaçlarla kullanılmadığı güvence altına alınmıştır",
      "auditorGuidance": "İncelenecek Husus: Emniyet verilerinin ticari, idari, performans değerlendirme (ceza veya ödül) veya sorumluluk atfetme gibi emniyet dışı amaçlarla kullanılmadığının (diğer birimlere ham/isimli veri paylaşılmadığının) sahada doğrulanması.\n\nKabul Edilebilir Kanıtlar: Personel Performans Değerlendirme Formu örnekleri (hata/olay raporlamanın bir performans/ceza kriteri olmadığını gösteren) ve birimler arası veri paylaşım kurallarını belirleyen iş akışları/protokoller.",
      "sourcePage": 51
    },
    {
      "id": 50,
      "htmlKey": "fr13-gs-17-aad01",
      "questionNo": 14,
      "questionCode": "SHGM.EYU.GS.17",
      "shortCode": "GS.17",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "TSHDEP 4.5",
      "question": "Kuruluş, olay raporlamaya ilişkin ilgili personelin görev ve sorumlulukları belirlemiş ve ilgili personeline gerekli erişim yetkisini vermiş mi?",
      "atomicCriterion": "İlgili personelin emniyet olay raporlaması ile ilgili görev, yetki ve sorumlulukları kuruluşun el kitaplarında ve görev tanımlarında net bir şekilde belirlenmiştir",
      "auditorGuidance": "İncelenecek Husus: Emniyet olay raporlamasına ilişkin görev, yetki ve sorumlulukların sadece emniyet birimi ile sınırlı kalmayıp, operasyonel personel için de ilgili mevzuata (SHT-OLAY/Reg. 376) atıf yapılarak net bir şekilde dokümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı (Sorumluluklar Bölümü) ve operasyonel unvanlara ait rastgele seçilen Görev Tanımı (JD) dokümanları.",
      "sourcePage": 52
    },
    {
      "id": 51,
      "htmlKey": "fr13-gs-17-aad02",
      "questionNo": 14,
      "questionCode": "SHGM.EYU.GS.17",
      "shortCode": "GS.17",
      "aadCode": "AAD02",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5",
      "question": "Kuruluş, olay raporlamaya ilişkin ilgili personelin görev ve sorumlulukları belirlemiş ve ilgili personeline gerekli erişim yetkisini vermiş mi?",
      "atomicCriterion": "Personelin raporlama sorumluluklarına dair farkındalığı; eğitimler, bültenler, görsel materyaller (afiş, poster) ile en üst seviyede tutulmaktadır",
      "auditorGuidance": "İncelenecek Husus: Personelin raporlama sorumluluklarına dair farkındalığının; eğitimler, görsel materyaller (afiş/poster) ve iletişim kampanyaları (örn. ödüllendirme sistemleri) ile sahada sürekli canlı tutulduğunun doğrulanması.\n\nKabul Edilebilir Kanıtlar: Ofis ve hangar alanlarındaki raporlama posterlerinin saha gözlemi, yayımlanan emniyet bülteni arşivleri ve personel ile yapılan farkındalık mülakat notları.",
      "sourcePage": 53
    },
    {
      "id": 52,
      "htmlKey": "fr13-gs-17-aad03",
      "questionNo": 14,
      "questionCode": "SHGM.EYU.GS.17",
      "shortCode": "GS.17",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5",
      "question": "Kuruluş, olay raporlamaya ilişkin ilgili personelin görev ve sorumlulukları belirlemiş ve ilgili personeline gerekli erişim yetkisini vermiş mi?",
      "atomicCriterion": "Personelin raporlama sorumluluklarına dair farkındalığı; yönetimin adil kültür desteği ile desteklenmektedir",
      "auditorGuidance": "İncelenecek Husus: Personelin olay raporlama konusundaki motivasyonunun, \"Adil Kültür\" prensibi (\"Raporlayın, Cezalandırılmayacaksınız\" teması) çerçevesinde doğrudan üst yönetim tarafından görünür bir şekilde desteklendiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: Üst yönetim (Sorumlu Müdür) tarafından tüm personele yayınlanmış Adil Kültür duyuruları, bülten mesajları veya video mesajları.",
      "sourcePage": 54
    },
    {
      "id": 53,
      "htmlKey": "fr13-gs-17-aad04",
      "questionNo": 14,
      "questionCode": "SHGM.EYU.GS.17",
      "shortCode": "GS.17",
      "aadCode": "AAD04",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5",
      "question": "Kuruluş, olay raporlamaya ilişkin ilgili personelin görev ve sorumlulukları belirlemiş ve ilgili personeline gerekli erişim yetkisini vermiş mi?",
      "atomicCriterion": "Olay raporlama sistemleri (yazılım portalı, fiziksel kutular vb.), tüm personelin çalışma alanlarından kolayca ulaşabileceği şekilde tesis edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Olay raporlama kanallarına (fiziksel veya dijital), bilgisayar başında çalışmayan saha personeli (teknisyen, yer hizmetleri vb.) dahil tüm çalışanların kendi çalışma alanlarından kolayca ve karmaşık olmayan arayüzlerle erişebildiğinin canlı testi.\n\nKabul Edilebilir Kanıtlar: Sahadaki kioskların / ortak bilgisayar terminallerinin gözlemi, mobil raporlama arayüzünün kullanım/giriş testi ve fiziksel kutuların erişilebilirlik konumu.",
      "sourcePage": 55
    },
    {
      "id": 54,
      "htmlKey": "fr13-gs-17-aad05",
      "questionNo": 14,
      "questionCode": "SHGM.EYU.GS.17",
      "shortCode": "GS.17",
      "aadCode": "AAD05",
      "auditType": "Yerinde",
      "reference": "TSHDEP 4.5",
      "question": "Kuruluş, olay raporlamaya ilişkin ilgili personelin görev ve sorumlulukları belirlemiş ve ilgili personeline gerekli erişim yetkisini vermiş mi?",
      "atomicCriterion": "Olay raporlama sistemlerine erişim için gerekli kullanıcı tanımları ve yetkilendirmeler, personelin görev alanına uygun olarak düzenlenmiş ve aktif durumdadır",
      "auditorGuidance": "İncelenecek Husus: Olay raporlama sistemine giriş için gerekli kullanıcı yetkilendirmelerinin güncel olduğunun, işe yeni giren veya departman değiştiren personelin sisteme hızlıca entegre edilerek erişim sorunu (\"yetkiniz yok\" hatası) yaşamadığının teyidi.\n\nKabul Edilebilir Kanıtlar: Bilgi İşlem (BT) Sistem Yetki Matrisi ve personelin sahadayken kendi şifresiyle sisteme sorunsuz girebildiğini gösteren örnek canlı giriş testi.",
      "sourcePage": 56
    },
    {
      "id": 55,
      "htmlKey": "fr13-zrs-18-aad01",
      "questionNo": 15,
      "questionCode": "SHGM.EYU.ZRS.18",
      "shortCode": "ZRS.18",
      "aadCode": "AAD01",
      "auditType": "Uzaktan",
      "reference": "Reg. (EU) No. 376/2014 Article 4(7), Article 4(8)",
      "question": "Kuruluş zorunlu olayların bildirilmesi için bir zaman dilimi belirlemiş mi?",
      "atomicCriterion": "İstisnai durumlar haricinde, zorunlu raporlamaya konu olan olayların, öğrenilmesini müteakip mümkün olan en kısa sürede ve 72 saati geçmeyecek şekilde, zorunlu rapor yapmaktan sorumlu gerçek kişi tarafından kuruluşa bildirilmesi kuralı, ilgili prosedürlerde açıkça tanımlanmıştır. (öncelikli olaylar dahil)",
      "auditorGuidance": "İncelenecek Husus: Zorunlu raporlamaya konu olan olayların, \"öğrenilmesini müteakip\" en kısa sürede ve azami 72 saat içerisinde personel (gerçek kişi) tarafından kuruluşa bildirileceği kuralının dokümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı veya Raporlama Prosedüründe yer alan 72 saat kuralı ve sürenin başlangıcını \"öğrenilme\" anı olarak tanımlayan ilgili paragraflar.",
      "sourcePage": 57
    },
    {
      "id": 56,
      "htmlKey": "fr13-zrs-18-aad02",
      "questionNo": 15,
      "questionCode": "SHGM.EYU.ZRS.18",
      "shortCode": "ZRS.18",
      "aadCode": "AAD02",
      "auditType": "Uzaktan",
      "reference": "Reg. (EU) No. 376/2014 Article 4(7), Article 4(8)",
      "question": "Kuruluş zorunlu olayların bildirilmesi için bir zaman dilimi belirlemiş mi?",
      "atomicCriterion": "İstisnai durumlar haricinde, zorunlu raporlamaya konu olan olayların, öğrenilmesini müteakip mümkün olan en kısa sürede ve 72 saati geçmeyecek şekilde kuruluş tarafından SHGM'ye bildirilmesi kuralı, ilgili prosedürlerde açıkça tanımlanmıştır. (öncelikli olaylar dahil)",
      "auditorGuidance": "İncelenecek Husus: Kuruluşun, zorunlu olayları \"öğrenmesini müteakip\" en kısa sürede ve azami 72 saat içerisinde SHGM'ye bildirmekle yükümlü olduğuna dair kurumsal kuralın dokümante edildiğinin teyidi.\n\nKabul Edilebilir Kanıtlar: SMS El Kitabı veya ilgili prosedürde yer alan SHGM'ye bildirim süresi kuralı.",
      "sourcePage": 58
    },
    {
      "id": 57,
      "htmlKey": "fr13-zrs-18-aad03",
      "questionNo": 15,
      "questionCode": "SHGM.EYU.ZRS.18",
      "shortCode": "ZRS.18",
      "aadCode": "AAD03",
      "auditType": "Yerinde",
      "reference": "Reg. (EU) No. 376/2014 Article 4(7), Article 4(8)",
      "question": "Kuruluş zorunlu olayların bildirilmesi için bir zaman dilimi belirlemiş mi?",
      "atomicCriterion": "Geçmişe dönük olay kayıtları incelendiğinde, bildirimlerin mevzuatta belirlenen 72 saatlik süre içerisinde yapıldığı doğrulanmaktadır",
      "auditorGuidance": "İncelenecek Husus: Geçmişe dönük olay bildirimlerinin, mevzuatta belirtilen 72 saatlik süre sınırı içerisinde yapıldığının zaman çizelgesi (olayın oluş/öğrenilme tarihi ile bildirim tarihi) üzerinden canlı teyidi.\n\nKabul Edilebilir Kanıtlar: Örneklem (Sampling) usulüyle seçilen son 3 aya ait rastgele 5-10 emniyet olayının bildirim formları ve tarih/saat damgalı sistem logları.",
      "sourcePage": 59
    },
    {
      "id": 58,
      "htmlKey": "fr13-zrs-18-aad04",
      "questionNo": 15,
      "questionCode": "SHGM.EYU.ZRS.18",
      "shortCode": "ZRS.18",
      "aadCode": "AAD04",
      "auditType": "Yerinde",
      "reference": "Reg. (EU) No. 376/2014 Article 4(7), Article 4(8)",
      "question": "Kuruluş zorunlu olayların bildirilmesi için bir zaman dilimi belirlemiş mi?",
      "atomicCriterion": "Hafta sonu, resmi tatil veya mesai saatleri dışındaki olayların bildirim sürelerini aksatmayacak bir raporlama akışı (nöbetçi sistem, otomatik sistem vb.) tesis edilmiştir",
      "auditorGuidance": "İncelenecek Husus: Hafta sonu, mesai saatleri dışı veya resmi tatillerde meydana gelen/öğrenilen olayların 72 saatlik bildirim süresini ihlal etmemesi için kurulan raporlama akışının (nöbetçi/otomatik sistem) fiilen çalıştığının teyidi.\n\nKabul Edilebilir Kanıtlar: Mesai dışı bildirimden sorumlu personelin iletişim/nöbet listeleri ile mesai dışı (örn. Pazar günü) gerçekleşmiş örnek bir olaya ait zaman damgalı bildirim kayıtları (e-posta veya sistem logu).",
      "sourcePage": 60
    }
  ]
};
